#!/usr/bin/env bash
# installing Nginx on a remote server

sudo apt-get  update -y
sudo apt-get  install nginx -y
echo "Hello World!"  | sudo tee /var/www/html/index.html
sed -i 's/# listen 80 default server;/listen 80 default server;/' /etc/nginx/sites-available/default
service nginx restart
