#!/usr/bin/env bash
# Configure HAProxy load balancer server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 297968-web-01 35.175.132.199
        server 297968-web-01 34.224.95.255" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
