#!/usr/bin/env bash
# Configure HAProxy load balancer server

sudo apt update -y
sudo apt install haproxy -y
echo "
front-end http-front
	bind *:80
	default-backend http-back
back-end http-back
	balance roundrobin
	server 297968-web-01 35.175.132.199:80 check
	server 297968-web-02 34.224.95.255:80 check" | tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart	
