#!/usr/bin/env bash
# print "Best School 10 times with "bad luck" and "good luck" at the 4th andd 8th iterations

i=1
while (( i <= 10 ))
do
	if (( i == 4 ))
	then
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
