#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
# Requirements:
# You must use the while loop (for and until are forbidden)

i=1
while (( i <= 13 ))
do
	(( j=1 ))
	while (( j <= 59 ))
	do
		echo $j
		(( j++ ))
	done
	if (( i <= 12 ))
	then
		echo "Hour: $i"
	fi
	(( i++ ))
done

